### ISSUE TITLE
Complete initial state

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/rust-cardano#610]
Here's a somewhat longer list of additional config parameters:

* Slot number per epoch
* Slot durations
* Stability
* Consensus requires a bunch of new extra parameters:
  * BFT:
    * a set of Bft `LeaderId`
  * Genesis:
    * parameter D (between 0.0 and 1.0)
    * parameter F (between 0.0 and 1.0)
    * note the Bft `LeaderId` is also useful in Genesis

I think there's a bunch of other parameters that are not on this list, but the big picture here is to have the blockchain fully configured through this message.

As additional side stuff to look into it:
* how to encode "float". likely we don't want ieee754 encoding, but a *decimal* based encoding with a specific precision and a specific range (0.0 to 1.0)
* macro(s) (if possible) to quickly add new parameter and their general encoding

**Comment by CodeSandwich** [comment]
@vincenthz The addition of consensus parameters from `genesis.yaml` perspective:
```yaml
# Current design
# problem: no way to have parameters in consensus 
blockchain_configuration:
  - [ block0-date, "1687616871" ]
  - [ discrimination, test ]
  - [ block0-consensus, genesis ]

# Plan A
# the forceful extension of current design, needs custom parsing,
# breaks idea of YAML
blockchain_configuration:
  - [ block0-date, "1687616871" ]
  - [ discrimination, test ]
  - [ block0-consensus, genesis:500:500:ad75ad875f9708730457cb98 ]

# Plan B
# the dreaded YAML format change, needs refactoring so config items can
# deserialize themselves without relying on blockchain_configuration knowing how to
# deserialize each of them (which I think is easy and healthy for the code anyway)
blockchain_configuration:
  - block0-date: "1687616871"
  - discrimination: test
  - block0-consensus:
    kind: genesis,
    param_d: 500,
    param_f: 500,
    leader: ad75ad875f9708730457cb98

# Plan C
# the multiplication of items, makes either deserialization or usage tricky,
# because data is not groupped, items have to be composed from
# multiple entries and verified for consistency
blockchain_configuration:
  - [ block0-date, "1687616871" ]
  - [ discrimination, test ]
  - [ block0-consensus, genesis:500:500:ad75ad875f9708730457cb98 ]
  - [ block0-consensus_param_d, 500 ]
  - [ block0-consensus_param_f, 500 ]
  - [ block0-consensus_leader, ad75ad875f9708730457cb98 ]
```
During today call I was trying to explain that plan A is a terrible idea and plan B is the one I want to follow. If I understood correctly you've proposed plan C. I still would go with plan B.
